import { AntdRegistry } from "@ant-design/nextjs-registry";
import { App, Flex, Layout } from "antd";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AppConfigProvider from "./_components/AppConfigProvider";
import Header from "./_components/Header";
import "./globals.css";
import { Content } from "antd/es/layout/layout";
import Footer from "./_components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ height: "100%" }}>
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{ height: "100%" }}
      >
        {/* Provided by AntD to extract and inject antd first creen styles into HTML to avoid page flicker */}
        <AppConfigProvider>
          <AntdRegistry>
            <App>
              <Layout>
                <Flex vertical style={{ height: "100%" }}>
                  <Header />
                  <Content style={{ flex: 1 }}>{children}</Content>
                  <Footer />
                </Flex>
              </Layout>
            </App>
          </AntdRegistry>
        </AppConfigProvider>
      </body>
    </html>
  );
}
