import { AntdRegistry } from "@ant-design/nextjs-registry";
import { App } from "antd";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AppConfigProvider from "./_components/AppConfigProvider";
import Header from "./_components/Header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Provided by AntD to extract and inject antd first creen styles into HTML to avoid page flicker */}
        <AppConfigProvider>
          <AntdRegistry>
            <App>
              <Header />
              {children}
            </App>
          </AntdRegistry>
        </AppConfigProvider>
      </body>
    </html>
  );
}
